const MOCK_TRACKS=[{id:'dQw4w9WgXcQ',title:'Never Gonna Give You Up',artist:'Rick Astley',duration:'3:33',source:'youtube'},{id:'9bZkp7q19f0',title:'Gangnam Style',artist:'PSY',duration:'4:13',source:'youtube'}]
export const MUSIC_PROVIDERS=[{id:'spotify',label:'Spotify'},{id:'deezer',label:'Deezer'},{id:'soundcloud',label:'SoundCloud'},{id:'youtube',label:'YouTube'}]
const api=String(import.meta.env.VITE_MUSIC_API_BASE_URL||import.meta.env.VITE_SPOTIFY_API_BASE_URL||'').replace(/\/$/,''),CACHE='rcMusicSearchCache:v3',TTL=7*24*60*60*1000,LIMIT=120,pending=new Map()
const norm=q=>q.trim().replace(/\s+/g,' ').toLowerCase()
const duration=s=>{const n=Number(s);if(!Number.isFinite(n)||n<=0)return'—';return`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`}
const media=t=>t.source==='spotify'?{...t,thumbnail:t.thumbnail||'',spotifyUrl:t.spotifyUrl||t.url||`https://open.spotify.com/track/${t.id}`,embedUrl:t.embedUrl||`https://open.spotify.com/embed/track/${t.id}`}:(t.source==='deezer'||t.source==='soundcloud')?{...t,thumbnail:t.thumbnail||'',externalUrl:t.externalUrl||t.url||'',previewUrl:t.previewUrl||''}:{...t,source:'youtube',thumbnail:t.thumbnail||`https://img.youtube.com/vi/${t.id}/hqdefault.jpg`,videoUrl:t.videoUrl||`https://www.youtube-nocookie.com/embed/${t.id}?autoplay=1&rel=0`}
function readCache(key){try{const c=JSON.parse(localStorage.getItem(CACHE)||'{}'),v=c[key];if(!v)return null;if(Date.now()-v.at>TTL){delete c[key];localStorage.setItem(CACHE,JSON.stringify(c));return null}return v.data}catch{return null}}
function writeCache(key,data){try{const c=JSON.parse(localStorage.getItem(CACHE)||'{}');c[key]={at:Date.now(),data};const keys=Object.keys(c).sort((a,b)=>c[b].at-c[a].at).slice(0,LIMIT);localStorage.setItem(CACHE,JSON.stringify(Object.fromEntries(keys.map(k=>[k,c[k]]))))}catch{}}
async function cached(key,fn){const old=readCache(key);if(old)return old;if(pending.has(key))return pending.get(key);const p=fn().then(x=>x||[]).catch(()=>[]).then(x=>{writeCache(key,x);return x}).finally(()=>pending.delete(key));pending.set(key,p);return p}
function decode(v=''){if(typeof document==='undefined')return v;const e=document.createElement('textarea');e.innerHTML=v;return e.value}
async function deezer(q){const endpoint=api?`${api}/deezer-search?q=${encodeURIComponent(q)}`:`https://api.deezer.com/search?q=${encodeURIComponent(q)}&limit=8`;const r=await fetch(endpoint);if(!r.ok)return[];const d=await r.json(),items=d.tracks||d.data||[];return items.map(t=>media({id:String(t.id),title:t.title,artist:t.artist?.name||t.artist||'Deezer',duration:t.duration?duration(t.duration):'Deezer',thumbnail:t.thumbnail||t.album?.cover_medium||t.album?.cover,previewUrl:t.previewUrl||t.preview,externalUrl:t.externalUrl||t.link||`https://www.deezer.com/track/${t.id}`,source:'deezer'}))}
async function spotify(q){if(!api)return[];const r=await fetch(`${api}/spotify-search?q=${encodeURIComponent(q)}`);if(!r.ok)return[];const d=await r.json();return(d.tracks||[]).map(t=>media({id:t.id,title:t.title,artist:t.artist,duration:t.duration,thumbnail:t.thumbnail,url:t.url,source:'spotify'}))}
async function soundcloud(q){const endpoint=api?`${api}/soundcloud-search?q=${encodeURIComponent(q)}`:import.meta.env.VITE_SOUNDCLOUD_CLIENT_ID?`https://api-v2.soundcloud.com/search/tracks?q=${encodeURIComponent(q)}&limit=8&client_id=${import.meta.env.VITE_SOUNDCLOUD_CLIENT_ID}`:'';if(!endpoint)return[];const r=await fetch(endpoint);if(!r.ok)return[];const d=await r.json(),items=d.tracks||d.collection||[];return items.map(t=>media({id:String(t.id),title:t.title,artist:t.artist||t.user?.username||'SoundCloud',duration:t.duration?duration(Number(t.duration)/1000):'SoundCloud',thumbnail:t.thumbnail||t.artwork_url||t.user?.avatar_url,previewUrl:t.previewUrl||t.preview||'',externalUrl:t.externalUrl||t.permalink_url||'',source:'soundcloud'}))}
async function youtube(q){if(!api){const m=MOCK_TRACKS.filter(t=>`${t.title} ${t.artist}`.toLowerCase().includes(q));return(m.length?m:MOCK_TRACKS).map(media)}const r=await fetch(`${api}/youtube-search?q=${encodeURIComponent(q)}`);if(!r.ok)return[];const d=await r.json();return(d.tracks||d.items||[]).map(t=>media(t.id?.videoId?{id:t.id.videoId,title:decode(t.snippet?.title),artist:decode(t.snippet?.channelTitle),source:'youtube'}:t))}
export async function searchTracks(query){const q=norm(query);if(!q)return[];const all=readCache(`all:${q}`);if(all)return all;for(const [name,fn] of [['spotify',spotify],['deezer',deezer],['soundcloud',soundcloud]]){const result=await cached(`${name}:${q}`,()=>fn(q));if(result.length){writeCache(`all:${q}`,result);return result}}const result=await cached(`youtube:${q}`,()=>youtube(q));writeCache(`all:${q}`,result);return result}
