export const MUSIC_PROVIDERS=[{id:'deezer',label:'Deezer'}]
const api=String(import.meta.env.VITE_MUSIC_API_BASE_URL||'').replace(/\/$/,''),CACHE='rcMusicSearchCache:v4',TTL=7*24*60*60*1000,LIMIT=120,pending=new Map()
const norm=q=>q.trim().replace(/\s+/g,' ').toLowerCase()
const duration=s=>{const n=Number(s);if(!Number.isFinite(n)||n<=0)return'—';return`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`}
const media=t=>t.source==='spotify'?{...t,thumbnail:t.thumbnail||'',spotifyUrl:t.spotifyUrl||t.url||`https://open.spotify.com/track/${t.id}`,embedUrl:t.embedUrl||`https://open.spotify.com/embed/track/${t.id}`}:(t.source==='deezer'||t.source==='soundcloud')?{...t,thumbnail:t.thumbnail||'',externalUrl:t.externalUrl||t.url||'',previewUrl:t.previewUrl||''}:{...t,source:'youtube',thumbnail:t.thumbnail||`https://img.youtube.com/vi/${t.id}/hqdefault.jpg`,videoUrl:t.videoUrl||`https://www.youtube-nocookie.com/embed/${t.id}?autoplay=1&rel=0`}
function readCache(key){try{const c=JSON.parse(localStorage.getItem(CACHE)||'{}'),v=c[key];if(!v)return null;if(Date.now()-v.at>TTL){delete c[key];localStorage.setItem(CACHE,JSON.stringify(c));return null}return v.data}catch{return null}}
function writeCache(key,data){try{const c=JSON.parse(localStorage.getItem(CACHE)||'{}');c[key]={at:Date.now(),data};const keys=Object.keys(c).sort((a,b)=>c[b].at-c[a].at).slice(0,LIMIT);localStorage.setItem(CACHE,JSON.stringify(Object.fromEntries(keys.map(k=>[k,c[k]]))))}catch{}}
async function cached(key,fn){const old=readCache(key);if(old)return old;if(pending.has(key))return pending.get(key);const p=fn().then(x=>x||[]).catch(()=>[]).then(x=>{writeCache(key,x);return x}).finally(()=>pending.delete(key));pending.set(key,p);return p}
async function deezer(q){const endpoint=api?`${api}/deezer-search?q=${encodeURIComponent(q)}`:`https://api.deezer.com/search?q=${encodeURIComponent(q)}&limit=8`;const r=await fetch(endpoint);if(!r.ok)return[];const d=await r.json(),items=d.tracks||d.data||[];return items.map(t=>media({id:String(t.id),title:t.title,artist:t.artist?.name||t.artist||'Deezer',duration:t.duration?duration(t.duration):'Deezer',thumbnail:t.thumbnail||t.album?.cover_medium||t.album?.cover,previewUrl:t.previewUrl||t.preview,externalUrl:t.externalUrl||t.link||`https://www.deezer.com/track/${t.id}`,source:'deezer'}))}
export async function searchTracks(query){const q=norm(query);if(!q)return[];const all=readCache(`all:${q}`);if(all)return all.filter(t=>t?.source==='deezer');const result=await cached(`deezer:${q}`,()=>deezer(q));const deezerResults=result.filter(t=>t?.source==='deezer');writeCache(`all:${q}`,deezerResults);return deezerResults}
